name: Auto Scraper Bot Verbose

on:
  schedule:
    # Chạy mỗi 30 phút
    - cron: "*/30 * * * *"
  workflow_dispatch:  # cho phép run thủ công

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml GitPython

      # Run verbose scraper
      - name: Run verbose scraper
        env:
          GITHUB_TOKEN_BOT: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          python scraper_multithread_verbose.py
